"""_add_relationships

Revision ID: 25c41f2cfb74
Revises: 4e8aa649bb5f
Create Date: 2024-02-18 21:16:29.120630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25c41f2cfb74'
down_revision: Union[str, None] = '4e8aa649bb5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gardens', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'plants', ['plant_id'], ['id'])
        batch_op.create_foreign_key(None, 'gardeners', ['gardener_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gardens', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
