"""Added quantity column to plants table

Revision ID: a4bcf11ee3bb
Revises: 1c7129c97672
Create Date: 2024-02-21 04:46:53.656627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4bcf11ee3bb'
down_revision: Union[str, None] = '1c7129c97672'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plants', sa.Column('quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plants', 'quantity')
    # ### end Alembic commands ###
